/*
LICENCIA JOSE JAVIER BO
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
Lista de paquetes:
 */
package ud2_01.vista.dialogos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import ud2_01.controlador.Controlador;
import ud2_01.controlador.dto.Empleado;
import ud2_01.vista.Texto;
import ud2_01.vista.venatana.Ventana;

/**
 *
 * @author Jose Javier BO
 */
public class FormularioEmpleado extends javax.swing.JDialog implements ActionListener{
    public static int EDITAR=0;
    public static int CREAR=1;
    
    int modo;
    Empleado empleado;
    
    Ventana ventana;
    /**
     * Creates new form FormularioEmpleado
     */
    public FormularioEmpleado(java.awt.Frame parent, int modo, Empleado empleado) {
        super(parent, true);
        initComponents();
        this.modo=modo;
        this.empleado=empleado;
        if (modo==EDITAR && empleado==null)
            throw new IllegalArgumentException("Empleado nulo no permitodo para la edicion");
        btnCancelar.addActionListener(this);
        btnGuardar.addActionListener(this);
        ventana= (Ventana)getParent();
        configurarModo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new java.awt.Label();
        panelEtiquetas = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbDNI = new javax.swing.JLabel();
        lbSueldo = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputApellidos = new javax.swing.JTextField();
        inputDNI = new javax.swing.JTextField();
        inputSueldo = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbTitulo.setAlignment(java.awt.Label.CENTER);
        lbTitulo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbTitulo.setText("CREAR EMPLEADO");

        lbID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbID.setText("ID");

        lbNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbNombre.setText("NOMBRE");

        lbApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbApellidos.setText("APELLIDOS");

        lbDNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDNI.setText("DNI");

        lbSueldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSueldo.setText("SUELDO");

        javax.swing.GroupLayout panelEtiquetasLayout = new javax.swing.GroupLayout(panelEtiquetas);
        panelEtiquetas.setLayout(panelEtiquetasLayout);
        panelEtiquetasLayout.setHorizontalGroup(
            panelEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEtiquetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelEtiquetasLayout.setVerticalGroup(
            panelEtiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEtiquetasLayout.createSequentialGroup()
                .addComponent(lbID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDNI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSueldo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        inputID.setEditable(false);

        inputSueldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        btnGuardar.setText("GUARDAR");
        btnGuardar.setActionCommand("guardar");

        btnCancelar.setText("CANCELAR");
        btnCancelar.setActionCommand("cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(panelEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputID)
                            .addComponent(inputNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(inputApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(inputDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(inputSueldo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelEtiquetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JTextField inputDNI;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JSpinner inputSueldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbDNI;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSueldo;
    private java.awt.Label lbTitulo;
    private javax.swing.JPanel panelEtiquetas;
    // End of variables declaration//GEN-END:variables

    private void configurarModo() {
        if (modo==CREAR){
            empleado=new Empleado(-1);
            lbID.setVisible(false);
            inputID.setVisible(false);
        }else{
            //rellenar formulario
            inputID.setText(""+empleado.getID());
            inputNombre.setText(empleado.getNombre());
            inputApellidos.setText(empleado.getApellidos());
            inputDNI.setText(empleado.getDNI());
            inputSueldo.setValue(empleado.getSueldo());
            lbID.setVisible(true);
            inputID.setVisible(true);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String ac=e.getActionCommand();
        switch (ac) {
            case "guardar":
                guardar();
                break;
            default:
               this.dispose();
        }
    }

    private void guardar() {
        String nombre=inputNombre.getText();
        String apellidos=inputApellidos.getText();
        String DNI=inputDNI.getText();
        double sueldo=(double) inputSueldo.getValue();
        
        if (nombre.trim().length()<1 || apellidos.trim().length()<1){
            ventana.msgError(Texto.ERROR_NOMBRE_APELLIDOS_VACIO);
            return;
        }
        if (DNI.length()!=9){
            ventana.msgError(Texto.ERROR_FORMATO_DNI);
            return;
        }
        
        empleado.setNombre(nombre);
        empleado.setApellidos(apellidos);
        empleado.setDNI(DNI);
        empleado.setSueldo(sueldo);
        
        if (modo==CREAR){
            if ( Controlador.insertar(empleado)==-1)
                ventana.msgError(Texto.ERROR_INSERTANDO_EMPLEADO);
            else
                dispose();
            
        }else if(Controlador.update(empleado)==-1){
                ventana.msgError(Texto.ERROR_ACTUALIZANDO_EMPLEADO);
        }else{
        dispose();
        }
            
        
    }
}
